### ISSUE TITLE
Taskbar icons disappears for a second

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WinDev#23]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | Windows 10 version 10.0.19041.388 |
| Processor Architecture | AMD64 | 
| Processor Type & Model | Core i5 (Skylake) | 
| Memory | 8GB |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | SSD 256GB | 
| Relevant apps installed  | ___ |

## Description

From time to time, the taskbar icons appears to be refreshed, but it takes such a long time that some icons disappear for about 1 sec. I'm not sure why/when it happens, it seems to be related to disk activity (files deleted/created ?)

## Steps to reproduce

No idea how to reproduce it, but it's quite frequent.

## Expected behavior

Icons disappear for 500ms-1sec.

## Actual behavior

Icons should not disappear, taskbar refresh should be seemless.

**Comment by asklar** [comment]
This sounds like a product bug, not a developer issue. I'd recommend filing a bug via Feedback Hub instead.

**Comment by bitcrazed** [comment]
@warpdesign - Not really a developer issue per se, but I can see that this would be annoying, so will ping the taskbar team for their feedback.

Please file via Feedback Hub and paste a link to the FBHub issue here to help us track.

**Comment by GeeLaw** [comment]
It seems that `SHChangeNotify` triggers a refresh, at least when the shell is notified for a file association change. Taskbar could continue using the old icon until the new version is fetched, instead of temporarily not showing the icon at all.

**Comment by warpdesign** [comment]
@GeeLaw not sure if that helps, but most of the time, when it happens, icons aren't updated. It's just that for some odd reason, there are refreshed, it takes a long time (during which there's no icon at all), and when it's done, it's the same icon I see.

**Comment by Eli-Black-Work** [comment]
I've seen this happen before, too. If I remember correctly, it often happens shortly after logging on after the machine has installed Windows updates when it was turned on/rebooted.

In my case, I seem to remember that  _all_ of the taskbar application icons disappear for a second or so.

**Comment by asklar** [comment]
@warpdesign kindly file feedback via Feedback Hub so the right team can investigate :)

**Comment by Eli-Black-Work** [comment]
By the way, is there any way to access the Feeback Hub online somewhere? My company doesn't let us install Feedback Hub on our work computers, so I can't submit feedback via that channel.

Thanks :)

**Comment by asklar** [comment]
that's a really good question @Bosch-Eli-Black ! Maybe @JeGentle will know!

**Comment by warpdesign** [comment]
Last time I checked @Bosch-Eli-Black, it wasn't possible.
> By the way, is there any way to access the Feeback Hub online somewhere? My company doesn't let us install Feedback Hub on our work computers, so I can't submit feedback via that channel.
> 
> Thanks :)

**Comment by warpdesign** [comment]
> @warpdesign kindly file feedback via Feedback Hub so the right team can investigate :)

I spent so many times reporting problems with the Feedback Hub without getting any feedback at all, I'm not sure I want to spend more time to re-create an issue over there.

I already reported a 3 or 4 issues on GitHub and already got more useful feedback than with the Feedback Hub where I spent time reporting dozens of problems for years.

Since it's very difficult to fully qualify a UI-related problem, the lack of having someone directly responding like here on GitHub to ask for more details is a big barrier and one of the reasons lots of feedbacks get lost IMHO.

**Comment by bitcrazed** [comment]
@Bosch-Eli-Black - Alas, no, there's no way to access issues in Feedback Hub via the web at this time. 

@warpdesign I appreciate that it may _appear_ as if FBHub is a black hole - and it's certainly a criticism the team hears and understands - but do know that feedback submitted via FBHub is routed to the team that owns the affected features/tech.

One thing that FBHub does VERY well is help capture click by click repro steps, and perf traces, logs, etc. on a per-area/issue-type basis. This is why, even here in the WinDev GH repo, we may ask you to file a FB Hub issue, and record a repro, so that we can capture the traces that help us diagnose the issue you're reporting.

Alas, FBHub wasn't built to support bi-directional discussions and the back & forth necessary to get to the root cause of the issue. FBHub receives a huge volume of feedback, often from non-technical users who wouldn't be amenable to carrying out some of the more advanced operations required to diagnose issues. As such, FB Hub wasn't designed as a bi-directional communications vehicle.

This is also why we created this repo - to provide a channel through which technical users, developers, etc., _can_ reach out and participate in issue diagnosis.

So please do continue to file general feedback via Feedback Hub, and direct more detailed technical/developer centric issues here where we can work together to get to the root of the issues you uncover.

Rich.

**Comment by orcmid** [comment]
> I've seen this happen before, too. If I remember correctly, it often happens shortly after logging on after the machine has installed Windows updates when it was turned on/rebooted.
> In my case, I seem to remember that _all_ of the taskbar application icons disappear for a second or so.

I don't have my task bar locked, so I don't know if this is happening.  There are startup cases where the icons on my Win10 desktop (where I open) seem to be repainted suddenly, whether they came up blank or not.  Sometimes I do see blank ones and they are restored properly in a few seconds.    

I have many icons around the periphery of my large screen, and 23 apps on the task bar.  I determine the morning startup is completed on appearance of the Bing Desktop search panel with new daily wallpaper arrives then or shortly thereafter :).  Same for my painfully-slow aging laptop.  Also much the same in a Windows Insider Hyper-V VM.  Also, on restarts I watch for the Bing Desktop search again showing up.  (And yes, I turn off my computers and the battery-backup every night.)

I've tolerated all of this for years.  It does not impede developer use in my case, although faster restarts would be nice.  I still prefer VS Code as editor of choice even though it does not seem to be as snappy as the earlier versions.  The only editor I have that opens more quickly is Notepad :).

**Comment by orcmid** [comment]
> @Bosch-Eli-Black - Alas, no, there's no way to access issues in Feedback Hub via the web at this time.
> 
> @warpdesign I appreciate that it may _appear_ as if FBHub is a black hole - and it's certainly a criticism the team hears and understands - but do know that feedback submitted via FBHub is routed to the team that owns the affected features/tech.

My impression is there are privacy issues around submissions to Microsoft, including via FBHub.  I don't mean just for Microsoft, but for submitters also.  That is a big difference over using a public issues system such as here for GitHub respositories.  We know we're working in the open in the case of public repos.

**Comment by warpdesign** [comment]
> but do know that feedback submitted via FBHub is routed to the team that owns the affected features/tech.

Allow me to have my doubts, especially for feedbacks reports in a language other than English since the text gets automatically translated into English.

**Comment by Poopooracoocoo** [comment]
>As such, FB Hub wasn't designed as a bi-directional communications vehicle.

wow. just wow. no wonder Windows 10 is what it is today.

**Comment by warpdesign** [comment]
> > As such, FB Hub wasn't designed as a bi-directional communications vehicle.
> 
> wow. just wow. no wonder Windows 10 is what it is today.

I guess it doesn't help indeed :/

**Comment by bitcrazed** [comment]
We are not typical Windows users. Most users don't want, nor have the patience or interest, to engage in a back and forth discussion to diagnose an issue they're having. That's why FBHub was designed primarily as a tool for users to drop issues into, and leave it up to the teams to diagnose and fix.

It's also why we created this repo - so that users like us, who do want to dig into the details, can.

Now ... let's please get back to the issue at hand ...

**Comment by sylveon** [comment]
The lack of bidirectional communication from FH is also what encourages some users to fill non-developer issues in this repo, because they feel like sending things to Feedback Hub is like talking to a wall.

**Comment by Eli-Black-Work** [comment]
@bitcrazed, My take is that FBHub might be fine for normal users, but it would be good to _also_ have a GitHub repository where "non-normal" Windows users could file issues and engage in bi-directional communication.

As you noted in your above comment, this is "why we created this repo - so that users like us, who do want to dig into the details, can." I think it's great that this repo exists, but as @asklar mentioned above, this repo isn't for product issues -- it's for developers issues.

I think what we need is a separate repo that _is_ for product issues. This wouldn't be meant to supplant FBHub but to complement it 🙂
