### ISSUE TITLE
Windows get resized when switch to fullscreen and back to desktop

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WinDev#24]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | Windows 10 version 10.0.19041.388 |
| Processor Architecture | AMD64 | 
| Processor Type & Model | Core i5 (Skylake) | 
| Memory | 8GB |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | SSD 256GB | 
| Relevant apps installed  | ___ |

## Description

When switching to full screen in some apps/games, when going back to the desktop, most of my windows get messed up: they are moved/resized.

## Steps to reproduce

- download dosbox
- open any windows and maximize them
- start dosbox and press `alt + enter`
- press `alt + enter` to switch back to window mode

## Expected behavior

Previously opened windows should be left untouched: positioned at the same position and with the same size.

## Actual behavior

Some windows get moved/resized.

See this video: https://youtu.be/UtB7P8f2j2A

As you can see, the Chrome Window takes most of the screen before switching to fullscreen and get resized when switching back to window mode.

**Comment by orcmid** [comment]
(Get this is not current meaning of "performance.")

I haven't seen such a blatant case.  What happens for some games that run full-screen is afterwards, my Bing Toolbar is moved from where I always park it to the middle of my screen somewhere.  I suspect some sort of (usually invisible) screen re-sizing/scaling that happens when the game starts up.  Since only some games do it, I suspect it is the game engine and not Windows that is the miscreant.

[PS: On a (Windows XP) tablet PC there was a problem if I changed verticality.  The remushing of desktop icons would be indelible, so I learned to arrange my desktop icons in a rotation-preserved corner.]

**Comment by warpdesign** [comment]
Since I remember it happening already in the XP days, I guess it's not an engine problems but rather a problem with Windows. Back then I didn't care. Right now I'm using my computer to do serious work as well as occasional playing.

**Comment by adrianghc** [comment]
> (Get this is not current meaning of "performance.")
> 
> I haven't seen such a blatant case. What happens for some games that run full-screen is afterwards, my Bing Toolbar is moved from where I always park it to the middle of my screen somewhere. I suspect some sort of (usually invisible) screen re-sizing/scaling that happens when the game starts up. Since only some games do it, I suspect it is the game engine and not Windows that is the miscreant.
> 
> [PS: On a (Windows XP) tablet PC there was a problem if I changed verticality. The remushing of desktop icons would be indelible, so I learned to arrange my desktop icons in a rotation-preserved corner.]

From my experience, this happens with games in exclusive full-screen mode that use a smaller screen resolution than the desktop, though I think that's a different case than the one in this issue.

**Comment by warpdesign** [comment]
@adrianghc I think that's what you describe. Games/apps use indeed a smaller screen resolution than the desktop.

**Comment by adrianghc** [comment]
> @adrianghc I think that's what you describe. Games/apps use indeed a smaller screen resolution than the desktop.

Yes, but considering the very strange aspect ratio your Chrome window acquires, I'm not sure that's what's at play here, is it? I'm also missing the usually more pronounced delay when entering and leaving exclusive full-screen.

**Comment by orcmid** [comment]
> > (Get this is not current meaning of "performance.")
> > I haven't seen such a blatant case. What happens for some games that run full-screen is afterwards, my Bing Toolbar is moved from where I always park it to the middle of my screen somewhere. I suspect some sort of (usually invisible) screen re-sizing/scaling that happens when the game starts up. Since only some games do it, I suspect it is the game engine and not Windows that is the miscreant.

> @adrianghc From my experience, this happens with games in exclusive full-screen mode that use a smaller screen resolution than the desktop, though I think that's a different case than the one in this issue.

I think that is my experience, the game opens to a default resolution that is less than my screen resolution and snaps to my full-screen faster than I can notice, probably before anything paints.  I don't think I have seen the case identified in this issue though.

**Comment by AvriMSFT** [comment]
Unfortunately, this issue is out of scope for this repo, so it won't be tracked here. BUT the team responsible for this issue gets feedback and bug reports via Feedback Hub! Please file this issue in the Feedback Hub under "Displays and Graphics -> Multiple Displays". Once you've done this, please paste the link here and I can go ahead and give the feedback an upvote. 

I've reached out to the team responsible and it looks like they're already tracking this bug and exploring solutions. Thanks for filing!

**Comment by Eli-Black-Work** [comment]
@AvriMSFT, This bug isn't about multiple displays. Should feedback still be filed there?

**Comment by AvriMSFT** [comment]
Yes. I spoke with a rep and they recommended you file there.

**Comment by warpdesign** [comment]
I filled an issue in FH: https://aka.ms/AAbz26p as suggested.

**Comment by AvriMSFT** [comment]
Upvoted
