### ISSUE TITLE
VS2019 set user location in simulator for testing navigation

### ISSUE THREAD

**Issue by NGame1** [microsoft/WinDev#30]
Hi there everyone and thanks for creating this repository for reporting problems. 
I have VS2019 Professional V16.6.5.
I'm trying to create a location-aware app but for testing tracking features and voice navigation and some other things I didn't find any way to simulate the user location. 
In Windows Phone/Windows 10 Mobile Emulator we had an option to set user location on the map for testing such programs, but in Simulator or in the Windows settings I didn't find anything for this. 
![image](https://user-images.githubusercontent.com/19765248/89695160-3cc9d180-d928-11ea-96fc-d5b71fe1ac42.png)

Seems, there was another report before for this missing feature here:
https://social.msdn.microsoft.com/Forums/windowsapps/en-US/8af845f5-6f18-4e30-a12c-cb1175894e4a/windows-10-simulator-set-location-button-is-missing
But no actions till today. 
Regards

**Comment by zooba** [comment]
Thanks for the report!

Sorry to keep giving you the run-around, but the best place to report this will be directly to the Visual Studio team at https://developercommunity.visualstudio.com/

I had a quick look and didn't see anything obvious in there for this already. I'd suggest when you post to include details of why your app needs this for testing - those kinds of reasons are more convincing than "this feature used to be there" (a lot of features used to be there, and mostly they get removed because it seems like nobody cares about them... so show us how much you care! :) )

**Comment by NGame1** [comment]
I got it I will open an article there so. 
The need of this feature is very simple. You want to create a navigation app and you need to test user location changes and your app behaviour. 
In my case I'm building a navigation app and it supports voice navigation and also text helps for navigation. For debugging my codes I have to be able to change the user location in a simulation and see if my voicr navigation or other parts works correctly or not. Now I have to build it on my Lumia 950XL and start walking around the city to debug my app really 😐😐😐
