### ISSUE TITLE
Task View animations are broken

### ISSUE THREAD

**Issue by adrianghc** [microsoft/WinDev#38]
I realize this issue is probably out of scope for this repo. However, emboldened by #12 and fed up with the years-long annoyance I decided to give it a try anyway. If you decide to close this issue because it does not fit this repo, I will understand.

## Environment

All Windows 10 versions since 1809.
The issue may be more pronounced when using scaling levels above 100%.

## Description

The animations when opening Task View / Timeline have been very annoyingly broken not for one release, not for two, but since 1809.

## Steps to reproduce

Open Task View. The issue may be more pronounced when using scaling levels above 100%.

## Expected behavior

I would expect a clean, fast, high-quality animation worthy of the world's most important desktop OS used by over a billion people, developed by one of the most valuable companies in the world.

## Actual behavior

You can stream a short screen recording showing this issue here: https://1drv.ms/v/s!AFJVlaoP229Vs4Qu

Window thumbnails flash and jump around at the end of the animation. Sometimes they all jump down and to the right. Sometimes they only jump to the right. Sometimes, in extremely rare cases, they don't jump at all.
Although not visible in the GIF, the "new desktop" button when there is only one desktop makes a small jump to the right as well.
Also not visible in the GIF: When having many window thumbnails, their layout may sometimes change, i.e. the rightmost window of a row jumps to the leftmost position of the next row at the end of the animation.

There have been many Feedback Hub issues about this over the years, e.g. this one: https://aka.ms/AA4y49e

If I may have a personal guess, it's that when the Timeline is loaded, not only is it shown under the thumbnails but the entire view is replaced by what Timeline renders. Unfortunately, it seems Timeline has a different logic to place the window thumbnails than the animation does. Again unfortunately, the jump also happens when Timeline is disabled. I also guess that when Timeline is disabled, some code for it still loads but simply shows nothing for the Timeline itself, but it still does for the thumbnail placements. Of course, I have no idea if any of this is true. However, supporting my guess is the fact that when using two screens, the animation is fine on the secondary screen, where Timeline doesn't show.

I use Task View and virtual desktops many, many times a day. Every time I have to deal with that horrendous animation. All this talk about design and all the beautiful sizzle reels are really nice, but in the end what people see is this. What does it say about Windows that this is still there after so many releases and almost two years? It's what people see when they try Surfaces in stores.

I don't think this requires many more words beyond what I've written. I can't really think of a satisfying explanation for why this has been so obviously broken for so long. Perhaps you can see my opening of this out-of-scope issue as a sign of my desperation, and a last call out into the void. Apologies for being so dramatic.

**Comment by lukeblevins** [comment]
The flickering animations need to be fixed, and have a slightly shorter duration in order for this area to match other desktops like gnome-shell on GNU/Linux. I would love to be productive with virtual desktops and Timeline, but this broken experience just puts a bad taste in my mouth. I hope the team can take a look at this one.

**Comment by asklar** [comment]
Thanks for the feedback @adrianghc! We're trying to keep the issues on this repo related to developer experience tools so unfortunately it's out of scope for this repo but I would really encourage you to file an issue via Feedback Hub.

**Comment by Felix-Dev** [comment]
@asklar Plenty of feedback about the Task View animation has already been posted on Feedback Hub. Why should another entry make a difference here?

**Comment by adrianghc** [comment]
> Thanks for the feedback @adrianghc! We're trying to keep the issues on this repo related to developer experience tools so unfortunately it's out of scope for this repo but I would really encourage you to file an issue via Feedback Hub.

@Felix_Dev is right here. This has been filed for years, upvoted for years, with no results. My trust in the Feedback Hub is not zero, it's below zero. I know you have all the good intentions and obviously I'm not blaming you personally for anything, but please, do us a favor and spare us the charade of "please file an issue via Feedback Hub". Time has proven to us (or at least to me) that it's a waste of time in the vast majority of cases. Certainly in this one.

I understand why you closed this issue, as I said early on. I was encouraged by a similar issue (#12) that was left open and even got an acknowledgement from the DWM team that it was being looked at - I'll leave it to you why all the feedback in the Feedback Hub over years couldn't achieve what one single out-of-scope GitHub issue could but you may place it in the context of my above paragraph.

If you could at least show this issue to the responsible people and let me know that they've acknowledged it, you would do me a tremendous favor. Just one email, one minute of your time. I would never have asked for more anyway.

**Comment by lhak** [comment]
Sometimes the window thumbnails even move to completely different positions for certain combinations of window sizes. So this issue definitely impacts developers. I also have to agree that I do not understand how such an obvious bug has not been fixed for years.

**Comment by orcmid** [comment]
@lhak Do you have games that might alter screen sizes during their startup?  Or even for operation? These can lead to messed-up desktops where Windows attempts to keep everything "in frame."  Those sometimes/usually do not snap back.   On tablets this can also happen when switching among orientations.  I have a couple that end up with a moved Bing Desktop search bar and I'm certain that is the interaction.  I suggest checking to see what applications that go full-screen are taking liberties with how they get to that point (and maybe see if they behave better as windowed, if that's an option).

**Comment by adrianghc** [comment]
> @lhak Do you have games that might alter screen sizes during their startup? Or even for operation? These can lead to messed-up desktops where Windows attempts to keep everything "in frame." Those sometimes/usually do not snap back. On tablets this can also happen when switching among orientations. I have a couple that end up with a moved Bing Desktop search bar and I'm certain that is the interaction. I suggest checking to see what applications that go full-screen are taking liberties with how they get to that point (and maybe see if they behave better as windowed, if that's an option).

I think he's talking about something different. He's talking purely about the thumbnails, not the app windows themselves; there is a problem with Task View where the layout of the thumbnail view changes at the end of the animation, e.g. instead of having three windows on the first row, the third window might jump to the first position of the second row and move all windows of the second row a position further etc. It only happens with some combinations of window (and consequently, thumbnail) sizes.

**Comment by bitcrazed** [comment]
Reopening this issue as we are indeed looking closely at various Windows UX issues such as described here. No guarantees or timelines to share at this time, but want to track this issue until resolved (one way or the other).

**Comment by adrianghc** [comment]
This is great news, thank you so much! Apologies about the overly dramatic tone in the issue description, but please bear with me - this problem is so glaring and I see it so many times a day, and it's been somewhat frustrating to deal with it for so many years with barely so much as an acknowledgement. It's great to get that now. :)

**Comment by lhak** [comment]
@adrianghc Yes, that is exactly what I meant. I have mostly observed this issue on a Surface Go, especially in portrait mode.

**Comment by lukeblevins** [comment]
If it helps the team's investigation, the animations appear to have gotten worse in recent dev channel flights. Can't pinpoint a build number, but certainly 20226

**Comment by adrianghc** [comment]
> If it helps the team's investigation, the animations appear to have gotten worse in recent dev channel flights. Can't pinpoint a build number, but certainly 20226

I'm not on that build, so out of curiosity, worse in what way? Do the thumbnails jump more or more erratically, or is there more lag?

**Comment by bitcrazed** [comment]
Thanks for the feedback, all. We do have a team that's looking at Task View UX design as part of a broad effort to improve various aspects of Windows' UX. To set expectations, know that improvements in this space won't start arriving until next year, but don't think nobody's looking - we do care and we are working on it. Stay tuned ;)

**Comment by adrianghc** [comment]
I appreciate you getting back to us with this information, thanks a lot. Thanks for setting the right expectations, and I look forward to seeing a fix to this (and other UX issues) sometime next year. :)

**Comment by lukeblevins** [comment]
@bitcrazed Thanks Rich!

It really helps set expectations when we get a tentative release period like this. 

Other teams within Microsoft are only allowed to say something along the lines of "not today" or "this won't happen overnight", so if at all possible let management know that we like this level of transparency!

Looking forward to hearing about further improvements in Windows.

**Comment by bitcrazed** [comment]
@duke7553 & @adrianghc Many thanks. I agree re. expectation-setting - its often useful to know if we're talking about something landing weeks/months/years out. And note that while I said some UX improvements won't start arriving until next year, no guarantees that improvements to task view will arrive next year either! But, as I said, know that we are actively looking into improvements in this space, so you're not being ignored 😜

**Comment by valinet** [comment]
Fixing a broken animation only next year, after it has been sitting like that for 2 years? I mean, c’mon, this is beyond infuriating... what happened, you lost the source code and have to reverse engineer it? If not, why does this have to ship with the rest of the supposed improvements next year? This is an annoying regression introduced when Timeline was introduced. This is a weekend job for any competent developer, which I am sure you have plenty, I think it is more of a management issue, and also not taking the time to look into it. I sincerely don’t understand, if you still have people familiar with the code, and have not lost it, it shouldn’t take this long to fix... same applies to #12. Also, #40 is still on 20H2, I don’t see how this is acceptable, why hasn’t a hotfix been issued immediately? I have to disable alt tab altogether now and use the XP interface as a workaround? What other OS in this world does not get alt tab right?

**Comment by duke7553** [comment]
@valinet Explanation: They seemingly forgot Windows 10 existed for two years while redirecting their best engineers to work on Windows 10X and Azure platform. We know this. Otherwise, they wouldn't neglect their core product this much. Brandon LeBlanc (awesome guy btw) actually answered me on Twitter about this. When I made a remark about the glaring design and usability issues in Windows 10 being withheld from users in a coordinated manner, he said this is "not correct" which would imply the problem isn't a secrecy issue but a lack of engineering altogether. 

When I continued, perhaps too far, about this implied lack of changes internally for Windows 10 he again stated this is "not true."

Based on these statements, which--due to the overall lack of transparency from the Windows team--we really shouldn't trust anymore, I can conclude that there is a combination of internal factors in play here preventing important work from being done on Windows. Because of this, I can safely state I will NOT recommend a Windows 10 device to pretty much anyone. Why?

ChromeOS managed to fix their multitasking experience over the course of a year. Going from a buggy unusable mess to a powerful joy to use. 

The half-baked experience has been offered to us for such an extended duration, that these are safe conclusions rather than overdramatic hyperboles.

**Comment by bitcrazed** [comment]
@valinet Appreciate your thoughts here, but this is a place to discuss issues, how to repro them, and track progress. It is not a place to vent personal frustrations. 

And it is **_definitely_** not a place to berate other engineering teams for their decisions that they had to arrive at after very careful deliberation. Every engineering team in every company has to balance a large number of factors including available engineering resources, schedules, organizational priorities, feedback, impact & scope of particular issues, etc.

Is it unfortunate that sometimes, UX issues appear? Yes. Would the team love to fix it? Absolutely. The fact that it hasn't yet been addressed may appear to some that "nobody cares", but that is not the case. The team is aware, and is working on improvements in this area, along with many others, delivered according to available resources, schedule, delivery vehicles, etc.

Please don't make wild presumptions stated as "facts".

**Comment by valinet** [comment]
I know, the cold hard truth may not sound good, we all have to be polite, we cannot express frustrations because we hurt feelings, even though, what? Did I attack anyone? I said, "competent developer[s], [...] I am sure you have plenty". That went unnoticed, you read only the part where I express, what? A reality... I am sorry, but I stand for what I said, as many have mentioned here as well, what's the conclusion when one browses through the plenty similar issues on the Feedback hub and no one at Microsoft answers? If I say "nobody cares", that's not it. But what is it? Is this the world we have to live into now, we hide behind big words yet we express nothing actually? I had enough of a bad day trying to fix some coworker's Windows installation after an update which kicked him into a temporary profile. I mean, yeah sure, if it were GNU/Linux, that's free, people work in their free time, I totally understand. But here, what, shut our mouths on our own hard earned money that we pay for this? If so, I said, make Windows free and open source and I won't ever complain again. I would look though the code and try to fix it.

Indeed, why not open source some shell stuff as well? Like, what's so proprietary in it? Again, I am going to get hated, but there is, I am sure, the fear that if Explorer is open sourced, people will compile it themselves disabling OneDrive ads and similar crap. That's the real reason imo. Besides that, please consider it, tell the team, management also, why isn't, for example, DWM open sourced...? I think Windows would be a very, very interesting story if its UX was open sourced, I am tired of taking years to look though symbols to do small tweaks. The community wants to help, you can easily see this on the many successful open source projects Microsoft hosts here, which all shape great (VS Code, Windows Terminal, winget), but some parts and some mentalities are so set in stone, on the other hand. That's how it looks to me, please do not misinterpret it again, I am not against you, I am not berating anyone, I actually like this OS and just wish it delivered more in a few areas.

**Comment by adrianghc** [comment]
While I understand why @valinet's comment sat wrong with @bitcrazed, I'd like to say that I agree with at least part of @valinet's sentiment, and the way he feels. Nobody is blaming any one specific person (at least he isn't, I think, and neither am I) and I understand perfectly that you have to deliberate carefully many times and balance many factors. Nobody ever said that's easy, and I'm sure you do it to the best of your conscience. And with such a large and complex codebase as that of Windows with so many engineering and financial and other decisions to make all the time, everyone with

**Comment by adrianghc** [comment]
While I understand why @valinet's comment sat wrong with @bitcrazed, I'd like to say that I agree with at least part of @valinet's sentiment, and the way he feels. Nobody is blaming any one specific person (at least he isn't, I think, and neither am I) and I understand perfectly that you have to deliberate carefully many times and balance many factors. Nobody ever said that's easy, and I'm sure you do it to the best of your conscience. And with such a large and complex codebase as that of Windows with so many engineering and financial and other considerations to make all the time, nobody in their right mind would expect a bug-free system, or be unforgiving of issues. But when issues are so glaring, and so obvious, and remain unacknowledged for so long, you do have to understand that that's where you must expect frustration to arise at some point, and where frankly it's understandable. In fact, what would it say about your customers and your product if nobody was frustrated about these issues? It would mean that we don't care about the product, at least the part of the product with those issues. If we didn't somewhat care, we wouldn't try so hard to get these issues fixed. When we see that all the feedback in that direction is being ignored for so long, it's only natural to conclude that perhaps it's simply that nobody cares. In reality, we do of course know that's not the case - but at some point, somebody in charge made the decision to leave this bug (and others) be for yet another release, and while, as I said, you do have to make that kind of decision and we do fully understand that, we don't have to always agree with it either. Certainly not after what will be, in the end, at least **seven** releases containing this issue (and #12).

**Comment by valinet** [comment]
@adrianghc To be frank, I am deeply disappointed by the discussion here. I don't know if you had time to read my reply to @bitcrazed answer, or just talking about my original reply, as he deleted it for no real reason in my opinion, other than disagreeing with him. I am totally in agreement with what you said above, and I am glad that I was quick enough to read it. What resonated with me the most is this part: "what would it say about your customers and your product if nobody was frustrated about these issues?". I am curious to hearing an answer to that as well, as it seems to me that "we are open to feedback", yet when the feedback is on a negative, but respectful, non offensive, but totally justifiable tone, in my opinion, you are dismissed because you think different. 

I took time to wrote a reply, as I took with this one as well, and despite being falsely accused of berating or disconsidering the team's work in the original reply, I know how that would feel, as that's how I feel after my reply was delete just because.

**Comment by bitcrazed** [comment]
Respectful constructive criticism is welcome here. But comments asking wildly off-topic questions like why we don't open source shell and/or file explorer are not.

We're grateful for the issues you all report, and for your help getting to their root-causes, but this simply isn't a place to vent.

**Comment by valinet** [comment]
The reply was partly about that, but whatever... considering your logic, my last reply, this one, @adrianghc's reply, or even your last one does not add anything to this, so I am waiting for you to enforce that logic on these as well, if that really is the rule around here. I thought we could talk about stuff here, okay, I was wrong, apparently talking and discussing things is not constructive anymore; I will go express my thoughts in the Feedback Hub, where I can safely be ignored.

And yeah, off topic again, but how can one believe in being an Insider, in reporting on Feedback Hub seeing all of this? If I were you, I'd issue a public apology for the way you treated some people and the issues they raised there, not zap me because I dared to raise a mere question. When you will really understand that users are what matters most to any product's success, maybe then the reputation Windows has will be gone. Don't tell me you don't know how Windows is perceived by ordinary people, maybe meditate on that, why is that so, is it because @valinet posted some seemingly off topic reply, or is it because of something else...?

**Comment by lukeblevins** [comment]
I agree with @valinet . I deleted my comment which detailed the neglect of Windows out of respect for the open source process, not because I changed my mind. What we need is more transparency. Telling us that good things are coming for the past two years doesn't change the fact that we require specifics on when the planned changes are coming to the Windows Shell.

**No open-sourcing required**

Almost every other Microsoft 365 service (Outlook online, OneDrive, Windows Virtual Desktop) benefits from this model because consumers expect to see roadmaps and commitments to deadlines like Apple and Google. 

@bitcrazed Is your management aware that we want this change? Feedback Hub it is then... 😢

**Comment by Poopooracoocoo** [comment]
~~the feedback hub~~ windows 10 is a joke.

anyway, this, along with all of the other Task View bugs and crashes started with v1803, not 
v1809.. It infuriates me every day. Early this year I tried v1703 in a VM and it was so nice. (but mah bash 😭)

You still can't rearrange/reorder virtual desktops. You can only name them with the 20H1 update. There are issues with thumbnails, thumbnail sizes, thumbnail placement and more. There are no public APIs for apps like SylphyHornEx to integrate into. Hell, that app shouldn't even exist! Timeline is dead so why isn't the new task view? If the new (as of v1709) touch keyboard could get back to performing as it used to in 2 years, why couldn't task view?

Edit: I don't understand why some of you not only believe but gave Rich's comments upvotes. This was reported before 1803 was even released to the production channel. Three years. They clearly don't care and don't use task view themselves. If you use them, you'll have seen it make Explorer crash. They wouldn't even isolate it from Explorer. It's a shame as virtual desktops are life changing. Imagine using your browser without windows or even without tabs! A few people have blindly supported MS for a while. I don't get it. These issues aren't lies. They aren't something you just disagree with. brain racking.

**Comment by bitcrazed** [comment]
@duke7553 & others

> @bitcrazed Is your management aware that we want this change? 

Yes. VERY, aware. 

While I really do appreciate how frustrating it can be to not have access to Microsoft's plans for a given thing (heck, venting my feedback [resulted in me returning to Microsoft to help fix the thing I'd vented about](https://www.bitcrazed.com/blog/2021/01/the-story-so-far/)), know that we do hear and appreciate all feedback about UX issues, inconsistencies, impediments, missing features, etc.

All I can tell you is that we're working hard to address many of these concerns. But for now you'll have to either:

1. Continue to be patient

or:

2. [Join Microsoft and help fix these things](https://careers.microsoft.com)

I hope that [what I've driven & delivered over the last 5 years](https://www.bitcrazed.com/blog/2021/01/the-story-so-far/) will give you just enough confidence that I am not aimlessly pacifying you and that worthwhile work is underway. Stay tuned.

**Comment by AvriMSFT** [comment]
We appreciate the feedback! Good news 🎉: The team who works on Task View is tracking the bug and its being investigated. The team actually take-in their issues via feedback hub though under Desktop Environment -> Alt-Tab and Task View :). We'll let the team know the issue has been filed here but as this issue is out of scope for this repository, please file another piece of feedback via feedback hub.

**Comment by Poopooracoocoo** [comment]
@AvriMSFT but how could this have been in windows for three years in the first place? surely not having testers was some kind of widespread joke about how most of them were fired, right??? i mean, the developer of the rewrite must've at least tested it...

and in the issue about windows search being slow i wasn't trying to be funny. not in the way rich understood at least. it was more of a tired-funny. a microsoft bot was threatening to close an issue that microsoft introduced and wasn't communicating with its users about. windows 8's search was actually pretty decent, despite all the flack it as an OS got. it was native too...
