### ISSUE TITLE
W10 "About" Obscures date of installed version/update.

### ISSUE THREAD

**Issue by orcmid** [microsoft/WinDev#44]
This rather cosmetic issue is relevant to me as an enthusiast/developer.  When I install feature updates and intermediate updates, the install date does not seem to change.  This has me be nervous about what I have installed (although one can tell by verifying a feature difference).

![VW10-2020-10-03-0951-VW10X-About](https://user-images.githubusercontent.com/3372580/95098507-9c075080-06e3-11eb-9c0c-3c731c6fff55.png)

In this image, the 2020-06-11 appears to be the date in which I created this Hyper-V VM Insider device.  The release preview 20H2 was installed this past first weekend of October 2020.  That is not reflected in the "Installed on" date.

On my main production desktop, now running (non-Insider) W10 Pro version 1909, there is "Installed on 2019-06-23 OS build 18363.1082."  That date us clearly incorrect.  (I would be running 2020, but it fails at one of the restart boot stages and reverts to the 1909 that I remain stuck with.)

**Comment by sylveon** [comment]
I disagree and prefer having the install date reflect when you first installed the OS.

In fact, my install date reflects the last time I installed a full fat feature update (not 1909 or 20H2 since those are just cumulative updates), and I dislike this behavior.

It shows 2020-04-22 but I've installed the OS back in November 2019.

![image](https://user-images.githubusercontent.com/6440374/95107398-db479880-0707-11eb-9c91-d0c071a536da.png)

**Comment by orcmid** [comment]
> I disagree and prefer having the install date reflect when you first installed the OS.
> 
It strikes me that rather than be a basis for disagreement, it would be good to eliminate the ambiguity of "Installed on" appearing related to "Version."  So long as it is explicit what the date represents, I can eliminate my nervousness around this UX defect.

**Comment by driver1998** [comment]
Build-to-build updates are really an OS reinstall and transfer your apps and settings afterwards, so it makes sense in a technical stand point.

But since Microsoft is now calling both "cumulative update with a feature switch" and "full fat updates which literally reinstall your OS" feature updates, they should come up with a more consistent definition.

**Comment by AvriMSFT** [comment]
Unfortunately this issue is out of scope for this repo, so it won't be tracked here. BUT the team responsible for this issue gets feedback and bug reports via Feedback Hub! Please file this issue in the Feedback Hub under "Install and Update -> Downloading Installing and Configuring". Once you've done this, please paste the link here and I can go ahead and give the feedback an upvote. 

Here's some information on the [20H2 deployment](https://blogs.windows.com/windowsexperience/2020/06/16/whats-next-for-windows-10-updates/).

**Comment by orcmid** [comment]
> Unfortunately this issue is out of scope for this repo, so it won't be tracked here. BUT the team responsible for this issue gets feedback and bug reports via Feedback Hub! Please file this issue in the Feedback Hub under "Install and Update -> Downloading Installing and Configuring". Once you've done this, please paste the link here and I can go ahead and give the feedback an upvote.

https://aka.ms/AAbxsya
