### ISSUE TITLE
Lag and very slow scrolling using trackpad in Firewall settings app

### ISSUE THREAD

**Issue by warpdesign** [microsoft/WinDev#48]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | [version 10.0.19041.508] |
| Processor Architecture | x64 | 
| Processor Type & Model | core i5 | 
| Memory | 8 Gb |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | 256 Gb | 
| Relevant apps installed  | ___ |

## Description

Horizontal scrolling using the touchpad in the firewall settings app is laggy and very slow when using the trackpad.

## Steps to reproduce

1.  Open the firewall app
2.  Select `incoming traffic rules` on the left
3.  Scroll horizontally using the trackpad

## Expected behavior

Scrolling should be fast/fluid and there should be no lag.

## Actual behavior

There is a lot of lag and it's very slow.

Video: https://youtu.be/-hqyGGxbH54

Feedback hub link: https://aka.ms/AA9xusb

**Comment by AvriMSFT** [comment]
Unfortunately this issue is out of scope for this repo, so it won't be tracked here. 

The Defender team would own this application so please file the feedback under the Security and Privacy -> Microsoft Defender Firewall and Network category. I will reach out to the Defender team to let them know about the scrolling behavior
