### ISSUE TITLE
opening a window "in the background" opens far away in alt+tab 

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/WinDev#66]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build | 10.0.19042.0 Microsoft Windows NT 10.0.19042.0 |
| Processor Architecture | AMD64  | 
| Processor Type & Model | intel | 
| Memory | ___ |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | ___ | 
| Relevant apps installed  | ___ |

## Description

opening a window "in the background" by repeatedly clicking on another window while it opens. pretty easy to repro with chromium. i open a window or an app from the taskbar. i see this often with chromium but i don't repeatedly click on another window of course. 

## Steps to reproduce

see above. soz. can't be bothered filling this out properly. might later.

## Expected behavior

to be next to my current window in alt+tab 

## Actual behavior

it opens far away. sometimes 6 windows away, sometimes it's the last window in alt+tab.

**Comment by AvriMSFT** [comment]
Unfortunately this issue is out of scope for this repo, so it won't be tracked here. BUT there's actually no need because this issue has been fixed in a recent build 🎉🙂 https://support.microsoft.com/en-us/topic/february-2-2021-kb4598291-os-builds-19041-789-and-19042-789-preview-6a766199-a4f1-616e-1f5c-58bdc3ca5e3b.

**Comment by Poopooracoocoo** [comment]
Only took several years. It really should be in scope of the repo. Rich said something like that.
