### ISSUE TITLE
Multi-display - windows popping up on other displays instead of the display I interact with

### ISSUE THREAD

**Issue by FletcherJ1** [microsoft/WinDev#68]
## Environment

| Item | Value | 
|---|---|
| OS, Version / Build |  Microsoft Windows NT 10.0.18363.0 | 
| Processor Architecture | AMD64 | 
| Processor Type & Model | Threadripper 2970WX | 
| Memory | 128GB |
| Storage Type, free / capacity (e.g. C: SSD 128GB / 512GB) | 1TB SSD, 470GB free | 
| Relevant apps installed  | Not applicable |

## Description
When developing with multiple displays I find that when I open an app on display 1 it actually appears on display 3 sometimes or possibly display 2, meaning I have to hunt for the window across the screens.

## Steps to reproduce
Open an app via one display, either through Windows start menu or clicking on the desktop and the window will appear sometimes on the same display and other times on a completely different display.

## Expected behavior
I'd love it if the the window opened on the display that I am interacting with, saving time and reducing confusion when the window doesn't appear on the display I am currently interacting with.

## Actual behavior
Written above in description tab.

**Comment by AvriMSFT** [comment]
@FletcherJ1 Unfortunately this issue is out of scope for this repo, so it won't be tracked here. BUT the team responsible for this issue gets feedback and bug reports via Feedback Hub! Please file this issue in the Feedback Hub under "Displays and Graphics -> Multiple Displays". Once you've done this, please paste the link here and I can go ahead and give the feedback an upvote. In the meantime, I've reached out to the team so they're now aware of the issue. 

Tip: Use Win +Shift +left/right to move your other monitors. Hopefully this helps a bit while the team explores solutions.
