### ISSUE TITLE
Tasklist doesn't read the correct status of UWP process

### ISSUE THREAD

**Issue by float34** [microsoft/WinDev#73]
Trying to read the status of **suspended** UWP process, but tasklist sees it as **running**:
![image](https://user-images.githubusercontent.com/25992594/104683968-0b400800-5709-11eb-9844-088f7ef6b169.png)

OS: Windows 10 Pro 20H2, build 19042.685

**Comment by sylveon** [comment]
As discussed on Discord, this is because UWP suspension is not the same as Win32 suspension, and `tasklist` only checks the latter.

It should be updated to also check UWP suspension. This can be done by calling `NtQuerySystemInformation` to get `PROCESS_EXTENDED_BASIC_INFORMATION`, and then the status of UWP suspension will be in the `IsFrozen` bit-field.

**Comment by AvriMSFT** [comment]
@sylveon Thanks for the solution 🙂. This should help @torquerrr

**Comment by Eli-Black-Work** [comment]
@AvriMSFT Can we reopen this? I think there are still actionable items on this, as per @sylveon's comment.
