### ISSUE TITLE
Windows 10 Updates information is broken and not reliable

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/WinDev#74]
A couple of months ago, the [Windows 10, version 1511 update history page](https://support.microsoft.com/en-us/help/4000824) moved to a new format and became broken. Some items are sometimes duplicate and some items are missing. For example, the KB4093109 update is not available, which is a big problem for me!

If you visit this page:
https://support.microsoft.com/en-us/topic/april-10-2018-kb4093109-os-build-10586-1540-a8ebe9db-7bf8-6876-4f9d-7abd7e9e91b3
You can find update KB4093109, but the sidebar is not shown and there's a JavaScript error on the page in the dev tools.
https://i.imgur.com/3bZDq7K.png

Starting from today, all of the pages for all Windows 10 versions moved to the "modern" style. All of them are buggy! For example, [here](https://support.microsoft.com/en-us/topic/august-14-2018-kb4343885-os-build-15063-1266-cf089a15-b46d-63f6-d899-ad8b9938b983) KB4343885 is listed twice. And I don't know what's missing.

Please fix this, it's very important for me. At the very least provide some text file with up-to-date information.

I don't know if that's the best place for this request. I tried the page feedback and the Microsoft forums about two weeks ago. Nothing happened. Please help me.

**Comment by justanotheranonymoususer** [comment]
I found [this page](https://winreleaseinfoprod.blob.core.windows.net/winreleaseinfoprod/en-US.html) (embedded as an iframe [here](https://docs.microsoft.com/en-us/windows/release-information/)), and I was happy that there actually is some reliable source of information about Windows Updates. But I found out that this page and [the "modern" page](https://support.microsoft.com/en-us/help/4000824) don't agree. And what's really bad, it's not that one has just more information - each of them mentions updates the other doesn't. So frustrating!

For example, the following updates are only listed in the iframe-d page:
```
KB4505057
KB4476976
KB4073290
KB4499418
KB3124262
KB3124263
KB3124200
KB3116900
KB3116908
KB3120677
KB3118754
KB3105211
```

On the other hand, the following updates are only listed in the "modern" page:
```
KB4599208-KB4525245 (all 1703 updates since 2019-11-12)
KB4016251
KB4023680
KB4016635
KB4010672
KB3216755
KB3200970
KB4016636
KB3198586
KB4016637
```

Please, help me, I spent so many hours on this. Fix the "modern" page to not have duplicates and missing items, or at least fix the gaps in the iframe-d version. And keep one version which is up-to-date, reliable, and not buggy. Please!

**Comment by justanotheranonymoususer** [comment]
A new bug: KB4341235 was listed [here](https://support.microsoft.com/en-us/help/4043454) but has now disappeared. Who can I talk about this? Please?

**Comment by justanotheranonymoususer** [comment]
And if you go [here](https://support.microsoft.com/en-us/help/4000823) and click on KB4601331, you're redirected to here with a broken sidebar again:
`https://support.microsoft.com/en-us/office/february-9-2021%e2%80%94kb4601331-os-build-10240-18842-6227d078-fef3-8d67-27e0-1882e6cb79ff?ui=en-US&rs=en-US&ad=US`

Office? What the heck? Please fix these pages.

**Comment by bitcrazed** [comment]
Not his direct responsibility, but hoping @mattwojo might be able to help route to whoever owns our KB content publishing system.

**Comment by mattwojo** [comment]
Investigating who owns this stuff. Thanks for bringing to our attention! ~Matt

**Comment by mattwojo** [comment]
@lizap - Do you own https://docs.microsoft.com/en-us/windows/release-health/release-information? 
Is this issue something that you can help with?

**Comment by mattwojo** [comment]
@CHorvath12 has claimed ownership and is actively investigating. Thanks Corrine!

**Comment by CHorvath12** [comment]
@justanotheranonymoususer 

Yesterday afternoon, I was made aware of your feedback and open questions. I can you started reaching out about a month ago. Since then, some of the issues you identified have been resolved while others remain open. 

For the side bar issues: We did encounter some issues during our migration to the updated platform but most have been resolved. We do have internal bugs open to resolve the remaining issues. 

For this item: A new bug KB4341235 was listed here but has now disappeared. 
I looked into the KB and it is still on the site as release notes for a mobile release in 2018: https://support.microsoft.com/help/4341235

For the content on the i-frame page (release information page) but not on the modern site. All of the release notes are posted but there is an issue with the side bar for which we do have an open bug to resolve. 
o	https://support.microsoft.com/help/4505057
o	https://support.microsoft.com/help/4476976
o	https://support.microsoft.com/help/4073290
o	https://support.microsoft.com/help/4499418
o	https://support.microsoft.com/help/3124262
o	https://support.microsoft.com/help/3124263
o	https://support.microsoft.com/help/3124200
o	https://support.microsoft.com/help/3116900
o	https://support.microsoft.com/help/3116908
o	https://support.microsoft.com/help/3120677
o	https://support.microsoft.com/help/3118754
o	https://support.microsoft.com/help/3105211

For the other set of content that is posted on Release notes but not on i-frame (Release information page)
- This is expected. The Release information page provides the KB IDs for Windows servicing updates of in-service Windows products though we do not remove content when products go out service.
- Also, for the initial feature release of the latest Windows product, these are not servicing packages and therefore are not shown on the Release information page
- On the modern, Release notes site, there are some knowledge base articles that are written that are not directly tied a servicing package but still have a KB ID or content for products or package types that we do not cover on the Release information page (Hololens, Surface Hub, etc)
- The list of 1703 IDs that are not reflected on Release information page (KB4599208-KB4525245 (all 1703 updates since 2019-11-12)) are due to the new release notes covering Surface Hub. The Release information page does not cover Surface Hub
- The remaining IDs that are shown on the modern Release notes site but not the Release information page: we will look into. 

I hope this information is helpful.

**Comment by justanotheranonymoususer** [comment]
Hi @CHorvath12, good to finally have somebody to talk to about that.

> For this item: A new bug KB4341235 was listed here but has now disappeared.
> I looked into the KB and it is still on the site as release notes for a mobile release in 2018: https://support.microsoft.com/help/4341235

Yes, it is available on that link, but:
* It can't be found [here](https://support.microsoft.com/en-us/help/4043454) under "Windows 10, version 1709 update history". It was available there before. You can also see that other "Windows 10 Mobile" items can be found there, like [KB4535289](https://support.microsoft.com/en-us/help/4535289).
* The page has no visible sidebar, I assume because it's not listed as a part of "Windows 10, version 1709 update history".

Aside from KB4341235 being missing there, my bigger concern is that there are other items I'm not aware of that are missing from the sidebar as well.

> For the content on the i-frame page (release information page) but not on the modern site. All of the release notes are posted [...]

You listed 12 items, but I see 24 KBs which are in the iframe but not on the modern site:

```
KB3074683, KB3081424, KB3081436, KB3081438, KB3081444, KB3081448, KB3081455, KB3093266, KB3097617, KB3105210, KB3105213, KB3116869, KB3124266, KB3105211, KB3116900, KB3116908, KB3118754, KB3120677, KB3124200, KB3124262, KB3124263, KB4499418, KB4073290, KB4505057
```

> The Release information page provides the KB IDs for Windows servicing updates of in-service Windows products though we do not remove content when products go out service.

I assume that you mean Windows mobile here?

> for the initial feature release of the latest Windows product, these are not servicing packages and therefore are not shown on the Release information page

What would be an example for that?

> there are some knowledge base articles that are written that are not directly tied a servicing package but still have a KB ID or content for products or package types

What would be an example for that?

Here are the items I currently see showed in the modern pages but not in the iframe:
```
Windows 10 Mobile:
KB4056342, KB4090912, KB4099572, KB4134196, KB4316692, KB4346644, KB4459082, KB4464853, KB4469220, KB4478936, KB4483203, KB4487695, KB4491736, KB4495357, KB4500154, KB4505390, KB4509104, KB4513172, KB4518514, KB4522809, KB4522811, KB4522812, KB4535289

Surface hub devices:
KB4525245, KB4530711, KB4534296, KB4537765, KB4540705, KB4550939, KB4556804, KB4561605, KB4565499, KB4567516, KB4571689, KB4577021, KB4580370, KB4586782, KB4592473, KB4599208, KB4601330

???:
KB4016637, KB4016636, KB3216755, KB4010672, KB4016635, KB4023680, KB4016251, KB4052314, KB4073117, KB4077675
```

In addition, there are other inconsistencies that I see:
* KB3147461: build 10240.16771 in iframe, build 10240.16769 in modern pages
* KB4601331: build 10240.18841 in iframe, build 10240.18842 in modern pages
* KB3206632: build 14393.576 in iframe, build 14393.571 in modern pages
* KB4038801: release date 2017-09-25 in iframe, 2017-09-28 in modern pages
* KB4057142: build 14393.2035 in iframe, build 14393.2034 in modern pages
* KB4020102: release date 2017-05-26 in iframe, 2017-05-25 in modern pages
* KB4032188: release date 2017-08-01 in iframe, 2017-07-31 in modern pages
* KB4457141: build 15063.1356 in iframe, build 15063.1358 in modern pages
* KB4490481: build 17763.404 in iframe, build 17763.402 in modern pages
* KB4490481: release date 2019-04-02 in iframe, 2019-03-26 in modern pages

**Comment by CHorvath12** [comment]
For all side bar missing items: I'll follow up with the team that managed the migration. This includes what you provided for KB4341235. They are aware of missing items and are working to resolve them. All of the KB articles you listed that are on the iframe page but not the release notes are live but missing from the side bar.

The initial rollout does not have a KB article as it is not a servicing update. I mean this for our Windows client releases. We list the GA date but there is no KB. See Version 21H2 and Version 2004 for examples.

Example of a knowledge base articles not connected to a servicing update. These are articles, not release notes: https://support.microsoft.com/en-us/topic/installing-and-searching-for-updates-is-slow-and-high-cpu-usage-occurs-in-windows-8-1-and-windows-server-2012-r2-f8231dba-ddcd-8ce7-e3aa-0f4d9051fd69 

https://support.microsoft.com/en-us/topic/how-to-query-the-microsoft-knowledge-base-by-using-keywords-and-query-words-1f39ec6a-edc7-e3dd-d265-77270160bfc6 

The Mobile and Surface Hub KBs you listed are not expected to be on the iframe/release information page. The Release information page covers servicing releases for "feature updates for Windows 10 are released twice a year, around March and September,"

The other KBs you listed under '??' and the inconsistencies you listed in the build and release dates -  I need to look in these.

**Comment by justanotheranonymoususer** [comment]
Hey there @CHorvath12, any progress regarding the inconsistencies?
Also, today I saw a new problem, this time regarding KB5007206.
It's listed under Windows 10 1607, but it seems like a mistake. Please confirm.
Link: https://support.microsoft.com/en-us/topic/windows-10-and-windows-server-2016-update-history-4acfbc84-a290-1b54-536a-1c0430e9f3fd

![image](https://user-images.githubusercontent.com/5781692/140987763-d8c368a6-a3fc-470a-b1f6-8e4d09463fad.png)

**Comment by CHorvath12** [comment]
Thank you for reaching back out. I reached out about the KB5007206 issue you noted above. The team was aware of the issue and the files have been updated and republished. We will continue to improve the quality of data published to both sites and make updates as needed. We have assessed your previous feedback and in reviewing the usage patterns of this older content we have found it is not substantial enough to justify updates. For future reports, please submit your findings to the following support channels so that any issues you identify can be directed to the teams supporting the pages. 
•	Feedback section at the bottom of the KB articles where you can provide a rating then feedback information
•	Answers.microsoft.com
•	Feedback Hub (app found in desktop)

**Comment by justanotheranonymoususer** [comment]
Hi again @CHorvath12,

> I reached out about the KB5007206 issue you noted above. The team was aware of the issue and the files have been updated and republished.

Thanks.

> We have assessed your previous feedback and in reviewing the usage patterns of this older content we have found it is not substantial enough to justify updates.

Too bad that having a high quality documentation is not substantial for you, but thank you for trying Corrine.

> For future reports, please submit your findings to the following support channels so that any issues you identify can be directed to the teams supporting the pages.

I tried, but unfortunately it didn't work for me.

> • Feedback section at the bottom of the KB articles where you can provide a rating then feedback information.

I did a couple of times, got no response back and saw no changes regarding my reports.

> • Answers.microsoft.com

I tried that too, I was sent back to the feedback section.

> • Feedback Hub (app found in desktop)

I can't use it since I don't use my Windows with a Microsoft account, that's our policy.

Also there's a new problem which broke my monitoring scripts - the KB5008212 update for Windows 10 version 2004 is missing from this page:
https://docs.microsoft.com/en-us/windows/release-health/release-information
But it's not missing here:
https://support.microsoft.com/en-us/topic/december-14-2021-kb5008212-os-builds-19041-1415-19042-1415-19043-1415-and-19044-1415-b46200db-74c3-450e-b200-51013957312a

Windows 10 version 2004 is End of service starting from today, but today's KB5008212 did get through.

![image](https://user-images.githubusercontent.com/5781692/146065929-9b7cc30b-beac-46e1-a5fe-5bc20e220767.png)

**Comment by mattwojo** [comment]
Thanks for bringing this to our attention @justanotheranonymoususer! We were able to identify the issue regarding the KB5008212 update for Windows 10 version 2004 and it should now be updated with the correct info. 
> https://docs.microsoft.com/windows/release-health/release-information
Thanks again for raising this awareness.

**Comment by bitcrazed** [comment]
Closing since this issue has been fixed and has had no subsequent feedback. Thanks for reporting & helping us resolve.
