### ISSUE TITLE
Is this repository dead?

### ISSUE THREAD

**Issue by riverar** [microsoft/WinDev#83]
Seems @bitcrazed @zooba and friends are busy with other projects and this repository isn't seeing much action. Issues aren't getting triaged, pull requests not getting reviewed, etc. Why should developers file their bugs here?

**Comment by zooba** [comment]
Responsiveness was always going to be the hardest part, but we're still definitely interested in hearing about the issues. We definitely have other projects that take our attention away from being public relations folk on GitHub, and only one of those is trying to get the feedback directed appropriately internally.

Basically all of these involve a large amount of bottom-up advocacy with the relevant teams to get the priorities raised - very few have been completely unknown, they just haven't risen to enough impact to annoy the teams (many developers have an annoying habit of just quietly working around things ;) ).

It's possible that in time it'll just get so overwhelming that we have to give up. That's a big part of the reason we've been angling for developer-specific feedback - because devs are underrepresented in other feedback channels, and that's who we've been wanting to amplify. But until that happens (and it's not actually my call - I'm a helper, not an owner here), having the feedback is more valuable than not having it, and we are trying to get it in front of the teams who can do something about it. Updating tags on GitHub is the step we're overlooking right now, sorry.
